### ISSUE TITLE
Choose currency of price when editing order

### ISSUE THREAD

**Issue by Kwaskoff** [fincubator/tellerbot#21]
![Imgur](https://imgur.com/70xduJM.png)

**Comment by r4rdsn** [comment]
@Kwaskoff Currency of price is based on currency in order, so when you invert it, you change it.
I can specify the currency in the last message of your screenshot and add the callback query button to change it without inverting the order, like when you create order, just so it's clear you can do that. There's no need to add another step.

**Comment by Kwaskoff** [comment]
you can see 64 USDT/ RUB
but this is wrong value
when I want fix it and edit it - tellerbot ask me value in usdt.. I can't say how much usdt in rub😢

**Comment by r4rdsn** [comment]
@Kwaskoff I just told you that you can - invert the order so price shows in RUB/USDT and then edit it.

**Comment by Kwaskoff** [comment]
ok, just add what current price is at the moment of editing
