### ISSUE TITLE
Tickers whitelist

### ISSUE THREAD

**Issue by Kwaskoff** [fincubator/tellerbot#42]
solution for ticker spam - listing ticker mechanism 
first list of tickers ![](https://i.imgur.com/K3J4gOE.jpg)
and ADD request button for unlisted tickers

**Comment by Kwaskoff** [comment]
USDT -> ETH, BTC, EOS, TRON, FINTEH, GDEX, RUDEX
GOLOS -> GOLOS, CYBER
TRON
BTS
CYBER
BTC -> RUDEX, GDEX, BTC
ETH -> RUDEX, GDEX, ETH
EOS -> RUDEX, GDEX, EOS
STEEM -> RUDEX, GDEX, STEEM
USD, RUB, EUR, CNY, UAH

**Comment by r4rdsn** [comment]
> USD, RUB, EUR, CNY, UAH
It would be easier if fiat and crypto were in one list as it would require just one check. Should there be two separate lists?

**Comment by Kwaskoff** [comment]
@r4rdsn as you wish

**Comment by r4rdsn** [comment]
Closed in 5c11541
