### ISSUE TITLE
add second blockchain to escrow - Cyberway

### ISSUE THREAD

**Issue by Kwaskoff** [fincubator/tellerbot#82]
All tokens on cyberway you can see here
https://explorer.cyberway.io/tokens

First of all make gateway for
GOLOS issued by gls
Precision: 3 decimals
This is standard dapp
https://docs.cyberway.io/devportal/system_contracts/cyber.token_contract

Code of GOLOS dapp is here
https://github.com/cyberway/golos.contracts

For ABI
https://developers.eos.io/manuals/eos/latest/cleos/command-reference/get/abi

CYBER issued by cyber
Precision: 4 decimals
It’s not dapp. It’s native token of the cyberway blockchain. Like EOS tokens in the EOSIO blockchain.

Public nodes
https://node-cyberway.golos.io
https://github.com/cyberway/cyberway.launch/blob/master/apinodes

Test account is usr11jwlrakn with GOLOS dapp tokens and CYBER native tokens
Active private key for request

**Comment by r4rdsn** [comment]
Closed in 150b22a.
